/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as zkTwittMainSol from "./ZkTwittMain.sol";
export type { zkTwittMainSol };
export type { Greeter } from "./Greeter";
export type { ZkTwitt } from "./ZkTwitt";
export type { ZkTwittNFT } from "./ZkTwittNFT";
