/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IZkTwittERC20__factory } from "./IZkTwittERC20__factory";
export { ZktTwittMain__factory } from "./ZktTwittMain__factory";
